# Site settings
title: Computer Science Maths
description: Information about maths topics useful for Computer Science, including implementations in JavaScript where appropriate
url: "https://alwaysbusy.github.io/"
baseurl: "/csmaths"

# Build settings
markdown: kramdown
